//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_CustomerMarketingActivities
    {
        public long ID { get; set; }
        public int J_ID_Customer { get; set; }
        public System.DateTime Date { get; set; }
        public string expert_name { get; set; }
        public System.DateTime next_contact_at { get; set; }
        public string customer_grade { get; set; }
        public string Descript { get; set; }
        public bool meeting_outcome { get; set; }
        public string activity_type { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
