//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Models/Metadata/crm_CustomerMarketingActivities.Metadata.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace cartonmohamad_sales.Models
{
    // کلاس اصلی auto-generated است؛ این partial فقط متادیتا و ناوبری را وصل می‌کند
    [MetadataType(typeof(CrmCustomerMarketingActivitiesMeta))]
    public partial class crm_CustomerMarketingActivities
    {
        // ناوبری به مشتری (با توجه به FK موجود در DB)
        public virtual Customer Customer { get; set; }
    }

    public class CrmCustomerMarketingActivitiesMeta
    {
        // PK: bigint NOT NULL
        [Key]
        public long ID { get; set; }

        // FK: int NOT NULL  → Customer(ID)
        [Display(Name = "مشتری")]
        [Required(ErrorMessage = "انتخاب مشتری الزامی است")]
        [ForeignKey(nameof(crm_CustomerMarketingActivities.Customer))]
        public int J_ID_Customer { get; set; }

        // Date: date NOT NULL  (فقط تاریخ)
        [Display(Name = "تاریخ فعالیت")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "تاریخ فعالیت را وارد کنید")]
        public DateTime Date { get; set; }

        // nvarchar(50) NOT NULL
        [Display(Name = "نام کارشناس")]
        [Required(ErrorMessage = "نام کارشناس الزامی است")]
        [StringLength(50, ErrorMessage = "حداکثر 50 کاراکتر")]
        public string expert_name { get; set; }

        // datetime2(7) NULL
        [Display(Name = "تماس بعدی")]
        [DataType(DataType.DateTime)]
        public DateTime? next_contact_at { get; set; }

        // char(10) NOT NULL  (اگر واقعاً در DB NOT NULL است)
        [Display(Name = "گرید مشتری")]
        [StringLength(10, ErrorMessage = "حداکثر 10 کاراکتر")]
        public string customer_grade { get; set; }

        // text NOT NULL  (DataAnnotations طول DB را تغییر نمی‌دهد؛ فقط ولیدیشن سمت کلاینت/سرور)
        [Display(Name = "توضیحات")]
        [StringLength(4000, ErrorMessage = "حداکثر 4000 کاراکتر")]
        public string Descript { get; set; }

        // bit NOT NULL
        [Display(Name = "نتیجه جلسه (سفارش گرفت)")]
        public bool meeting_outcome { get; set; }

        // nvarchar(100) NOT NULL
        [Display(Name = "نوع فعالیت")]
        [StringLength(100, ErrorMessage = "حداکثر 100 کاراکتر")]
        public string activity_type { get; set; }
    }
}
