//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    // اگر نام جدول دقیقاً Customer است، این خصیصه لازم نیست
    // [Table("Customer")]
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.crm_CustomerMarketingActivities = new HashSet<crm_CustomerMarketingActivities>();
            this.Info_Compuni = new HashSet<Info_Compuni>();
            this.Tb_Order = new HashSet<Tb_Order>();
        }

        [Key]
        public int ID { get; set; }

        // نام مشتری (اجباری، حداکثر طول، نمایشی فارسی)
        [Required(ErrorMessage = "نام مشتری الزامی است")]
        [StringLength(100, ErrorMessage = "حداکثر طول نام مشتری 100 کاراکتر است")]
        [Display(Name = "نام مشتری")]
        public string Customer1 { get; set; }

        // نام شرکت (اختیاری، حداکثر طول و ایندکس یکتا در صورت نیاز)
        [StringLength(100)]
        [Display(Name = "نام شرکت")]
        // اگر EF 6.1+ دارید و می‌خواهید یکتا باشد، این را فعال کنید:
        // [Index("IX_CompanyName", IsUnique = true)]
        public string company_name { get; set; }

        // وضعیت (مثلاً active/inactive) — اگر مقادیر ثابت دارید، پیشنهاد enum + مپ پایین
        [StringLength(50)]
        [Display(Name = "وضعیت")]
        public string Status { get; set; }

        // خوش‌حسابی: good/average/bad
        [StringLength(10)]
        [Display(Name = "وضعیت پرداختی")]
        [RegularExpression(@"^(good|average|bad)$",
            ErrorMessage = "مقدار معتبر برای وضعیت پرداختی: good, average, bad")]
        public string payment_behavior { get; set; }

        // فیلد همزمانی (اختیاری ولی مفید برای جلوگیری از overwrite)
        [Timestamp]
        public byte[] RowVersion { get; set; }

        // ناوبری‌ها
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_CustomerMarketingActivities> crm_CustomerMarketingActivities { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Info_Compuni> Info_Compuni { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Order> Tb_Order { get; set; }
    }
}
