//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalCharge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinalCharge()
        {
            this.Tb_Body_Order = new HashSet<Tb_Body_Order>();
        }
    
        public int final_charge_id { get; set; }
        public string name { get; set; }
        public bool is_active { get; set; }
        public bool is_required { get; set; }
        public string calc_type { get; set; }
        public short priority { get; set; }
        public string apply_on { get; set; }
        public Nullable<decimal> percent_rate { get; set; }
        public Nullable<long> fixed_amount_irr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Body_Order> Tb_Body_Order { get; set; }
    }
}
