//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
// Models/FinalCharge.cs  (auto-generated by EDMX)
using System.Collections.Generic;

namespace cartonmohamad_sales.Models
{
    public partial class FinalCharge
    {
        public FinalCharge()
        {
            this.Tb_Body_Order = new HashSet<Tb_Body_Order>();
        }

        public int final_charge_id { get; set; }
        public string name { get; set; }
        public bool is_active { get; set; }
        public bool is_required { get; set; }
        public string calc_type { get; set; }   // "percent" | "fixed"
        public short priority { get; set; }
        public string apply_on { get; set; }   // "subtotal" | ...
        public decimal? percent_rate { get; set; }
        public long? fixed_amount_irr { get; set; }

        public virtual ICollection<Tb_Body_Order> Tb_Body_Order { get; set; }
    }
}
