//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Compuni
    {
        public int ID { get; set; }
        public int J_ID_Customer { get; set; }
        public string address_factory { get; set; }
        public string address_sales_office { get; set; }
        public string address_warehouse { get; set; }
        public string address_dispatch { get; set; }
        public string phone_factory { get; set; }
        public string phone_sales_office { get; set; }
        public string phone_procurement_manager { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
