//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverheadCost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OverheadCost()
        {
            this.Tb_Body_Order = new HashSet<Tb_Body_Order>();
        }
    
        public int overhead_id { get; set; }
        public string name { get; set; }
        public bool is_required { get; set; }
        public string calc_method { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> qty_per_meter { get; set; }
        public long unit_price_irr { get; set; }
        public bool show_on_invoice { get; set; }
        public int price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Body_Order> Tb_Body_Order { get; set; }
    }
}
