//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperCombo
    {
        public int combo_id { get; set; }
        public int product_id { get; set; }
        public string combo_name { get; set; }
        public string combo_kind { get; set; }
        public Nullable<int> top_liner_paper_id { get; set; }
        public Nullable<int> flute_be_paper_id { get; set; }
        public Nullable<int> middle_paper_id { get; set; }
        public Nullable<int> flute_c_paper_id { get; set; }
        public Nullable<int> bottom_liner_paper_id { get; set; }
        public bool is_active { get; set; }
        public string notes { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Tb_Paper Tb_Paper { get; set; }
        public virtual Tb_Paper Tb_Paper1 { get; set; }
        public virtual Tb_Paper Tb_Paper2 { get; set; }
        public virtual Tb_Paper Tb_Paper3 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Tb_Paper Tb_Paper4 { get; set; }
    }
}
