//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.PaperCombos = new HashSet<PaperCombo>();
            this.ProductImages = new HashSet<ProductImage>();
            this.Tb_Body_Order = new HashSet<Tb_Body_Order>();
        }
    
        public int product_id { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string product_type { get; set; }
        public int tirage { get; set; }
        public Nullable<byte> layers_count { get; set; }
        public Nullable<byte> pieces_count { get; set; }
        public string door_type { get; set; }
        public Nullable<byte> doors_count { get; set; }
        public Nullable<decimal> length_cm { get; set; }
        public Nullable<decimal> width_cm { get; set; }
        public Nullable<decimal> height_cm { get; set; }
        public Nullable<int> sheets_per_order { get; set; }
        public Nullable<int> units_per_sheet { get; set; }
        public Nullable<int> bottoms_per_sheet { get; set; }
        public Nullable<decimal> flap_total_cm { get; set; }
        public Nullable<decimal> flap_top_cm { get; set; }
        public Nullable<decimal> flap_bottom_cm { get; set; }
        public Nullable<decimal> die_to_die_length_cm { get; set; }
        public Nullable<decimal> mold_width_cm { get; set; }
        public Nullable<short> bottoms_per_mold { get; set; }
        public Nullable<decimal> industrial_length_cm { get; set; }
        public Nullable<decimal> industrial_width_cm { get; set; }
        public Nullable<decimal> carton_consumption_m2 { get; set; }
        public Nullable<short> grammage_gsm { get; set; }
        public Nullable<decimal> industrial_area_m2 { get; set; }
        public string flute_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperCombo> PaperCombos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Body_Order> Tb_Body_Order { get; set; }
    }
}
