//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int image_id { get; set; }
        public int product_id { get; set; }
        public string file_url { get; set; }
        public string storage_provider { get; set; }
        public string alt_text { get; set; }
        public string caption { get; set; }
        public bool is_primary { get; set; }
        public int sort_order { get; set; }
        public string mime_type { get; set; }
        public Nullable<int> width_px { get; set; }
        public Nullable<int> height_px { get; set; }
        public Nullable<long> size_bytes { get; set; }
        public string checksum_sha1 { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
