//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Body_Order
    {
        public long ID { get; set; }
        public long J_ID_order { get; set; }
        public int J_ID_Production { get; set; }
        public Nullable<int> final_charge_id { get; set; }
        public int J_id_OverheadCosts { get; set; }
    
        public virtual FinalCharge FinalCharge { get; set; }
        public virtual OverheadCost OverheadCost { get; set; }
        public virtual Product Product { get; set; }
        public virtual Tb_Order Tb_Order { get; set; }
    }
}
