//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Catgori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Catgori()
        {
            this.Tb_join_Categori_Paper = new HashSet<Tb_join_Categori_Paper>();
        }
    
        public int ID { get; set; }
        public string Categori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_join_Categori_Paper> Tb_join_Categori_Paper { get; set; }
    }
}
