//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartonmohamad_sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_join_Categori_Paper
    {
        public int ID { get; set; }
        public int J_ID_Catgori { get; set; }
        public int J_ID_PAper { get; set; }
        public string Value { get; set; }
        public bool type { get; set; }
    
        public virtual Tb_Catgori Tb_Catgori { get; set; }
        public virtual Tb_Paper Tb_Paper { get; set; }
    }
}
